/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'Build': '建造',
    'Delete': '删除',
    'Delete All Objects': '删除所有对象',
    'Filter mode': '过滤模式',
    'Ray afterglow decay': '射线余辉衰变',
    'Show highest rate': '显示最高比率',
    'Solar panel mode': '太阳能板模式',
    'Sound': '声音',
    'Stats': '统计',
    'Upgrades': '升级',
    'Detector': '检测器',
    'Light Source': '光源',
    'Normal': '正常',
    'Solar Panel': '太阳能板',
    'off': '关',
    'paused': '暂停',
    'nil': 'nil',
    'none': '无',
    'quick': '快速',
    'persist': '持续',
    'stopped': '停止',
    'there\'s no audio': '没有音频',
    'true': '是',
    'unavailable': '不可用',
    'nada': 'nada',
    'muted': '静音',
    'false': '否',
    'disabled': '禁用',
    'dis-enabled': '禁用',
    'blocked': '阻塞',
    'Gamma Rays Only': '只有伽马射线',
    'Filter': '过滤器',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'No Light': '无光线',
    'X-ray Only': '只有X射线',
    'Infrared Only': '只有红外线',
    'Green Only': '只有绿色',
    'Blue Only': '只有蓝色',
    'Red Only': '只有红色',
    'Ultraviolet Only': '只有紫外线',
    'All Light': '所有光',
    'A panel that will only allow certain wavelengths of light through, depending on the mode.': '一种只允许特定波长的光通过的面板，这取决于模式。',
    'A solar panel which converts incoming light rays into energy. It has various modes which can make use of different light for improved energy generation.\n\nCurrently, it will produce energy off of the red, green, and blue visible light spectrum.': '一种将入射光线转换成能量的太阳能电池板。 它具有多种模式，可以利用不同的光来改善能量的产生。\n\n当前，它将从红色，绿色和蓝色可见光谱中产生能量。',

    //树游戏
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Light Filter\nA material that can filter out different kinds of light. Unfiltered light loses no energy.\n\n": "滤光片\n一种可以滤除各种光的材料。 未经过滤的光不会损失任何能量。\n\n",
    "Large Mirror\nA larger reflective panel. Reflects rays out at an equal but opposite angle as of incoming lights. Effective on all electromagnetic waves.\n\nCurrent upgrades allows for the mirror to reflect light with 50% of the incoming energy.\n\n": "大镜子\n更大的反光板。 以与入射光相同但相反的角度反射光线。 对所有电磁波均有效。\n\n当前的升级允许反射镜以入射能量的50％反射光。\n\n",
    "Solar Panel\nAn object that collects light and produces power. Can be upgraded to optimize for different types of electromagnetic waves.\n\n": "太阳能电池板\n收集光并发电的物体。 可以升级以针对不同类型的电磁波进行优化。\n\n",
    "Detector\nAn informational panel that describes the photons passing through it. Does not affect the rays.\n\n": "检测器\n一个信息面板，描述通过它的光子。 不影响光线。\n\n",
    "Light Source\nIt produces light. That\'s what you're trying to get. You should get the light. That would be good.\n\n": "光源\n它会产生光。 那就是你想要得到的。 你应该得到光。 那会很好。\n\n",
    "Convex Lens\nA thin lens which bends light rays towards the center axis. Effective on all electromagnetic waves.\n\nCurrent upgrades allows light to pass through with 90% of the incoming energy.\n\n": "凸透镜\n将光线弯曲到中心轴的薄透镜。 对所有电磁波均有效。\n\n当前升级允许光以90％的入射能量通过。\n\n",
    "Increase maximum normalizers by 1": "将最大标准化器增加1",
    "An informational panel that describes the photons passing through it.\n\n": "一个信息面板，描述通过它的光子。\n\n",
    "Increase energizer efficiency by 10%\n\n": "激励效率提高10％\n\n",
    "Increase maximum energizers by 1\n\n": "将能量上限增加1\n\n",
    "Increase maximum filters by 3\n\n": "将过滤器上限增加3 \n\n",
    "Increase maximum filters by 5\n\n": "将过滤器上限增加5 \n\n",
    "Increase maximum large mirrors by 2\n\n": "将大镜子上限增加2\n\n",
    "Increase maximum large mirrors by 5\n\n": "将大镜子上限增加5\n\n",
    "Increase maximum light sources by 1\n\n": "将光源上限增加1\n\n",
    "Unlocks gamma ray cascader\n\n": "解锁伽玛射线级联器\ n \ n",
    "Unlocks x-ray tubes\n\n": "解锁X射线管\n\n",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^Rays per second\: (.+)\nAverage infrared\: (.+)\nAverage red\: (.+)\nAverage green\: (.+)\nAverage blue\: (.+)\nAverage ultraviolet\: (.+)\nAverage xray\: (.+)\nAverage gamma\: (.+)$/, '每秒射线：$1 \n平均红外线：$2 \n平均红色：$3 \n平均绿色：$4 \n平均蓝色：$5 \n平均紫外线：$6 \n平均射线：$7 \n平均伽马：$8'],
    [/^Rays per second\: (\d+)$/, '每秒射线：$1'],
    [/^(.+)W \((.+)W$/, '$1W \($2W'],
    [/^(.+)W \((.+)W\/s\) \[(.+)W\/s]$/, '$1W \($2W\/秒\) \[$3W\/秒\]'],
    [/^Owned\: (.+)\nMaximum\: (.+)$/, '拥有：$1 \n最大数量：$2'],
    [/^Congratulations!\nYou managed to obtain an unbelievable amount of power!\nIt has been about (.+) minutes since you started.\nYou've reached the end of all current content. However, I may continue to develop more after the end of the jam.\nIn the meantime, click anywhere to return to the game.$/, '恭喜！\n您获得了令人难以置信的强大功能！\n自开始以来已经有$1分钟的时间。\n您已经达到所有当前内容的结尾。 但是，在卡纸结束后，我可能会继续开发更多游戏。\n同时，单击任意位置以返回游戏。'],
    [/^Total game ticks: (.+)\nMax power: (.+)\nTotal power: (.+)\nHighest power per second: (.+)\nCoolest person ever: You$/, '总游戏tick：$1 \n最大功率：$2 \n总功率：$3\n每秒最高功率：$4 \n有史以来最酷的人：您'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^\n\nCost\: (.+)$/, '成本：$1'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);